[functions]
  external_node_modules = ["express", "ejs"]
  node_bundler = "esbuild"
  included_files = ["views/**", "public/**"]

# Catch-all redirect for API calls
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true